# Generated by Django 4.2.2 on 2023-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.TextField(default='default notes for old ones'),
            preserve_default=False,
        ),
    ]
